# Generated by Django 3.2.7 on 2021-10-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_researchinterests_teacherresearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='research_areas',
        ),
    ]
