# Generated by Django 3.2.7 on 2021-10-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_teacherresearchfk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchinterests',
            old_name='name',
            new_name='research_name',
        ),
        migrations.CreateModel(
            name='TeacherMany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('research_areas', models.ManyToManyField(to='pages.ResearchInterests')),
            ],
        ),
    ]
