# Generated by Django 3.2.7 on 2021-10-25 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20211025_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchinterests',
            old_name='research_name',
            new_name='name',
        ),
    ]
