# Generated by Django 3.2.7 on 2021-10-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_research_name_researchinterests_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherResearch',
        ),
        migrations.RemoveField(
            model_name='teacherresearchfk',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teachermany',
            name='citations_all',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teachermany',
            name='citations_since_2016',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teachermany',
            name='college',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teachermany',
            name='hindex_all',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teachermany',
            name='hindex_since_2016',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teachermany',
            name='i10index_all',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teachermany',
            name='i10index_since_2016',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='TeacherResearchFK',
        ),
    ]
