# Generated by Django 3.2.7 on 2021-10-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20211025_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermany',
            name='links',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
