# Generated by Django 3.2.7 on 2021-10-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_teachermany_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermany',
            name='all_research_areas',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
